//! Compile-time prompt templates for the Loom workflow phases.
//!
//! Each template family lives in its own submodule; the `Template` impls are
//! generated by Askama (`#[derive(Template)]`) and validated at build time —
//! a missing context field is a compile error.
//!
//! Agent-generated content (`previous_failure`, `title`, `description`,
//! `existing_tasks`) is wrapped in `<agent-output>...</agent-output>` markers
//! in the template bodies as a best-effort prompt-injection mitigation.
//!
//! # Public Contract
//!
//! `templates` is a public-contract crate. External Rust consumers
//! (e.g. RAG pipelines, domain-specific review tools) compose their own
//! templates from the exposed typed building blocks
//! ([`PinnedContext`], [`PreviousFailure`], [`LoopContext`],
//! [`ReviewContext`]) and the `PARTIAL_*` partial-string constants
//! below. Loom's own workflow templates (`plan_*`, `todo_*`, `run`,
//! `review`, `msg`) are internal — consumers compose with the partials
//! and typed contexts, not with the workflow shells.

pub mod criterion_status;
pub mod finding;
pub mod msg;
pub mod plan;
pub mod previous_failure;
pub mod review;
pub mod run;
pub mod todo;

pub use criterion_status::{CriterionResult, CriterionStatus};
pub use finding::{
    ConcernToken, Finding, FindingParseError, FindingTarget, FindingValidator, LOOM_FINDING_PREFIX,
    TargetKind,
};
pub use msg::{ClarifyBead, ClarifyOption, MsgContext};
pub use plan::{PlanNewContext, PlanUpdateContext};
pub use previous_failure::{
    BadWalk, DriverNoticeCause, PREVIOUS_FAILURE_MAX_LEN, PreviousFailure, STDERR_TAIL_PER_BLOCK,
    VerifierFailure,
};
pub use review::{ReviewContext, ReviewSource};
pub use run::LoopContext;
pub use todo::{TodoNewContext, TodoUpdateContext};

/// Project-overview + style-rules pinning shape, exposed as a typed
/// building block external consumers can embed in their own template
/// contexts to mirror Loom's pinning ergonomics without re-deriving the
/// field names.
///
/// `pinned_context` is the project-overview body (`docs/README.md` by
/// default in Loom's binary); `style_rules` is the style-rules document
/// body (`docs/style-rules.md` by default). Both arrive pre-rendered —
/// the template engine treats them as opaque strings.
#[derive(Debug, Clone)]
pub struct PinnedContext {
    pub pinned_context: String,
    pub style_rules: String,
}

/// `partial/companions_context.md` — list companion paths declared on the spec.
pub const PARTIAL_COMPANIONS_CONTEXT: &str =
    include_str!("../templates/partial/companions_context.md");

/// `partial/context_pinning.md` — pin the project-overview file.
pub const PARTIAL_CONTEXT_PINNING: &str = include_str!("../templates/partial/context_pinning.md");

/// `partial/decomposition_discipline.md` — pin the audit-before-fan-out
/// rule on `todo_new` / `todo_update`: every authored bead must
/// correspond to evidence-confirmed missing work (read off
/// `criterion_status` + representative implementations), or the agent
/// emits `LOOM_CLARIFY` on the molecule epic per the *Options Format
/// Contract* in `specs/gate.md`.
pub const PARTIAL_DECOMPOSITION_DISCIPLINE: &str =
    include_str!("../templates/partial/decomposition_discipline.md");

/// `partial/chat_interview.md` — pin the chat discipline for planning
/// interviews: questions and answers flow as prose, and the planning
/// agent does not use Claude Code's structured option-picker tool
/// (`AskUserQuestion`) or any equivalent multi-choice UI. Included only
/// by `plan_new` and `plan_update`.
pub const PARTIAL_CHAT_INTERVIEW: &str = include_str!("../templates/partial/chat_interview.md");

/// `partial/findings_walk.md` — sole carrier of the `LOOM_FINDING:` /
/// `LOOM_CONCERN:` colon-suffixed wire format. Pinned by `review.md`;
/// the anti-drift verifier (see `specs/gate.md` § Findings and
/// Minting) fails any other template under
/// `crates/loom-templates/templates/` that restates the wire format.
pub const PARTIAL_FINDINGS_WALK: &str = include_str!("../templates/partial/findings_walk.md");

/// `partial/progress_markers.md` — `LOOM_COMPLETE` / `LOOM_NOOP`,
/// the two "work is done" terminators. Pinned by every worker /
/// planning template (`plan_new`, `plan_update`, `todo_new`,
/// `todo_update`, `run`, `review`).
pub const PARTIAL_PROGRESS_MARKERS: &str = include_str!("../templates/partial/progress_markers.md");

/// `partial/self_report_markers.md` — `LOOM_BLOCKED` / `LOOM_CLARIFY`,
/// the two "cannot finish" terminators. Pinned alongside
/// `progress_markers.md` so each phase template surfaces the full
/// terminator surface.
pub const PARTIAL_SELF_REPORT_MARKERS: &str =
    include_str!("../templates/partial/self_report_markers.md");

/// `partial/chat_marker_final_turn_only.md` — restrict `LOOM_COMPLETE`
/// emission to the **final** assistant turn of a multi-turn chat
/// session. Multi-turn templates (`msg`, `plan_new`, `plan_update`)
/// include this alongside the progress / self-report marker partials
/// so the "end your response with the marker" instruction does not
/// get read as "every response." One-shot worker templates (`run`,
/// `todo_*`, `review`) deliberately omit this partial — every
/// response in those phases IS the final output, so the wrap-up
/// restriction does not apply.
pub const PARTIAL_CHAT_MARKER_FINAL_TURN_ONLY: &str =
    include_str!("../templates/partial/chat_marker_final_turn_only.md");

/// `partial/interview_modes.md` — describe the "one by one" / "polish
/// the spec" interview sub-modes.
pub const PARTIAL_INTERVIEW_MODES: &str = include_str!("../templates/partial/interview_modes.md");

/// `partial/invariant_clash.md` — describe the invariant-clash awareness scan.
pub const PARTIAL_INVARIANT_CLASH: &str = include_str!("../templates/partial/invariant_clash.md");

/// `partial/plan_stage_rubric.md` — gate the planning interview on
/// completeness / coherence / invariant-clash.
pub const PARTIAL_PLAN_STAGE_RUBRIC: &str =
    include_str!("../templates/partial/plan_stage_rubric.md");

/// `partial/review_rubric.md` — per-diff review rubric.
pub const PARTIAL_REVIEW_RUBRIC: &str = include_str!("../templates/partial/review_rubric.md");

/// `partial/scratchpad.md` — pin the per-session scratchpad path.
pub const PARTIAL_SCRATCHPAD: &str = include_str!("../templates/partial/scratchpad.md");

/// `partial/sibling_spec_editing.md` — authorize cross-spec edits during
/// a planning session.
pub const PARTIAL_SIBLING_SPEC_EDITING: &str =
    include_str!("../templates/partial/sibling_spec_editing.md");

/// `partial/spec_conventions.md` — pin the spec-conventions document.
pub const PARTIAL_SPEC_CONVENTIONS: &str = include_str!("../templates/partial/spec_conventions.md");

/// `partial/spec_header.md` — render spec label, path, active molecule.
pub const PARTIAL_SPEC_HEADER: &str = include_str!("../templates/partial/spec_header.md");

/// `partial/style_rules.md` — pin the style-rules file.
pub const PARTIAL_STYLE_RULES: &str = include_str!("../templates/partial/style_rules.md");
