issue-prefix: "lm"
import.auto: false
dolt:
    mode: server
    auto-start: false
sync-branch: "beads"
sync:
    mode: dolt-native
    remote: ".git/beads-worktrees/beads/.beads/dolt-remote"
export:
    auto: false
    git-add: false
